app = "api"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "3333"  # Porta que a aplicação escuta
  NODE_ENV = "dev"
  DATABASE_URL = "postgresql://docker:docker@localhost:5432/ilumeo?schema=public"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 3333
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false
